-- Database: bd_patrocars

-- DROP DATABASE IF EXISTS bd_patrocars;

CREATE DATABASE bd_patrocars
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE MONTADORA (
	MONT_ID SERIAL PRIMARY KEY NOT NULL,
	NOME TEXT NOT NULL,
	PAIS TEXT NOT NULL,
	ANO_FUNDACAO INT NOT NULL
);


CREATE TABLE MODELO_VEICULO (
	MOD_ID SERIAL PRIMARY KEY NOT NULL,
	NOME TEXT NOT NULL,
	MONT_ID INT NOT NULL REFERENCES MONTADORA(MONT_ID),
	VALOR_REFERENCIA DECIMAL(10, 2) NOT NULL,
	MOTORIZACAO INT NOT NULL,
	TURBO BOOLEAN NOT NULL,
	AUTOMATICO BOOLEAN NOT NULL,
	FOREIGN KEY (MONT_ID) REFERENCES MONTADORA(MONT_ID) ON DELETE CASCADE
);


CREATE TABLE VEICULO (
	VEIC_ID SERIAL PRIMARY KEY NOT NULL,
	MOD_ID INT NOT NULL REFERENCES MODELO_VEICULO(MOD_ID),
	COR TEXT NOT NULL,
	ANO_FABRICACAO INT NOT NULL,
	ANO_MODELO INT NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	PLACA TEXT NOT NULL,
	VENDIDO BOOLEAN NOT NULL,
	FOREIGN KEY (MOD_ID) REFERENCES MODELO_VEICULO(MOD_ID) ON DELETE CASCADE
);

INSERT INTO MONTADORA VALUES (DEFAULT, 'TOYOTA', 'JAPÃO', 1920);
INSERT INTO MODELO_VEICULO VALUES (DEFAULT, 'MODELO1', 1, 30000.00, 1, TRUE, TRUE);
INSERT INTO VEICULO VALUES (DEFAULT, 1, 'VERMELHO', 2024, 1, 30500.00, 'AAAA', FALSE);